HotelSystem.Admin/Models/ErrorViewModel.cs
using System;

namespace HotelSystem.Admin.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HotelSystem.Admin/Models/Guests/GuestDetailsOutputModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HotelSystem.Admin.Models.Guests
{
    public class GuestDetailsOutputModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string EGN { get; set; }

        public string CardNumber { get; set; }
    }
}

HotelSystem.Admin/Models/Guests/GuestInputModel.cs
using System.ComponentModel.DataAnnotations;

namespace HotelSystem.Admin.Models.Guests
{
    public class GuestInputModel
    {
        [Required]
        [MaxLength(50)]
        public string Name { get; set; }

        [Required]
        [MaxLength(20)]
        [MinLength(8)]
        public string CardNumber { get; internal set; }
    }
}

HotelSystem.Admin/Models/Guests/GuestOutputModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HotelSystem.Admin.Models.Guests
{
    public class GuestOutputModel
    {
        public string Name { get; set; }

        public string CardNumber { get; internal set; }
    }
}

HotelSystem.Admin/Models/Statistics/StatisticsOutputModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HotelSystem.Admin.Models.Statistics
{
    public class StatisticsOutputModel
    {
        public int TotalReservations{ get; set; }
    }
}

HotelSystem.Admin/Controllers/AdministrationController.cs
using HotelSystem.Common.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Refit;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace HotelSystem.Admin.Controllers
{
    [AuthorizeAdministrator]
    public abstract class AdministrationController : Controller
    {
        protected async Task<ActionResult> Handle(Func<Task> action, ActionResult success, ActionResult failure)
        {
            try
            {
                await action();
                return success;
            }
            catch (ApiException exception)
            {
                this.ProcessErrors(exception);
                return failure;
            }
        }

        private void ProcessErrors(ApiException exception)
        {
            if (exception.HasContent)
            {
                JsonConvert
                    .DeserializeObject<List<string>>(exception.Content)
                    .ForEach(error => this.ModelState.AddModelError(string.Empty, error));
            }
            else
            {
                this.ModelState.AddModelError(string.Empty, "Internal server error.");
            }
        }
    }
}

HotelSystem.Admin/Controllers/GuestsController.cs
using HotelSystem.Admin.Models.Guests;
using HotelSystem.Admin.Services.Guests;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace HotelSystem.Admin.Controllers
{
    public class GuestsController : AdministrationController
    {
        private readonly IGuestsService guests;

        public GuestsController(IGuestsService guests)
        {
            this.guests = guests;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
            => View(await this.guests.All());

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var guest = await this.guests.Details(id);

            var guestForm = new GuestOutputModel { CardNumber = guest.CardNumber, Name = guest.Name };

            return View(guestForm);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, GuestOutputModel model)
            => await this.Handle(
                async () => await this.guests
                    .Edit(id, new GuestInputModel { Name = model.Name, CardNumber = model.CardNumber}),
                success: RedirectToAction(nameof(Index)),
                failure: View(model));
    }
}

HotelSystem.Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using HotelSystem.Admin.Models;

namespace HotelSystem.Admin.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HotelSystem.Admin/Controllers/IdentityController.cs
using HotelSystem.Admin.Infrastructure;
using HotelSystem.Admin.Models.Identity;
using HotelSystem.Admin.Services.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using HotelSystem.Common.Infrastructure;
using System.Threading.Tasks;

namespace HotelSystem.Admin.Controllers
{
    public class IdentityController : AdministrationController
    {
        private readonly IIdentityService identityService;

        public IdentityController(
            IIdentityService identityService)
        {
            this.identityService = identityService;
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(UserInputModel model)
            => await this.Handle(
                async () =>
                {
                    var result = await this.identityService
                        .Login(model);

                    this.Response.Cookies.Append(
                        InfrastructureConstants.AuthenticationCookieName,
                        result.Token,
                        new CookieOptions
                        {
                            HttpOnly = true,
                            Secure = true,
                            MaxAge = TimeSpan.FromDays(1)
                        });
                },
                success: RedirectToAction(nameof(GuestsController.Index), "Guests"),
                failure: View("../Home/Index", model));

        [AuthorizeAdministrator]
        public IActionResult Logout()
        {
            this.Response.Cookies.Delete(InfrastructureConstants.AuthenticationCookieName);

            return RedirectToAction(nameof(HomeController.Index), "Home");
        }
    }
}

HotelSystem.Admin/Controllers/StatisticsController.cs
using HotelSystem.Admin.Services.Statistics;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HotelSystem.Admin.Controllers
{
    public class StatisticsController : AdministrationController
    {
        private readonly IStatisticsService statistics;

        public StatisticsController(IStatisticsService statistics)
            => this.statistics = statistics;

        public async Task<IActionResult> Index()
            => View(await this.statistics.All());
    }
}

HotelSystem.Admin/Views/Guests/Edit.cshtml
@model GuestInputModel

@{ ViewData["Title"] = "Edit Guest"; }

<div class="row">
    <div class="col-lg-4 offset-lg-4">
        <h2>Edit Guest</h2>
    </div>
</div>

<div class="row">
    <div class="col-lg-4 offset-lg-4">
        <form asp-controller="Guests" asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly"></div>
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" id="name" placeholder="Enter name">
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CardNumber"></label>
                <input asp-for="CardNumber" class="form-control" id="phone-number" placeholder="Enter phone number">
                <span asp-validation-for="CardNumber" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>

HotelSystem.Admin/Views/Guests/Index.cshtml
@model IEnumerable<GuestDetailsOutputModel>

@{ ViewData["Title"] = "Guests"; }

<div class="row">
    <div class="col-lg-4">
        <h2>All Dealers</h2>
    </div>
</div>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">EGN</th>
            <th scope="col">Card number</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var guest in Model)
        {
<tr>
    <td>@guest.Id</td>
    <td>@guest.Name</td>
    <td>@guest.EGN</td>
    <td>@guest.CardNumber</td>
    <td>
        <a class="btn btn-primary"
           asp-area=""
           asp-controller="Guests"
           asp-action="Edit"
           asp-route-id="@guest.Id">
            Edit
        </a>
    </td>
</tr>
}
    </tbody>
</table>

HotelSystem.Admin/Views/Home/Index.cshtml
@model UserInputModel

@{ ViewData["Title"] = "Home Page"; }

<div class="row">
    <div class="col-lg-4 offset-lg-4">
        <h2>Login</h2>
    </div>
</div>

<div class="row">
    <div class="col-lg-4 offset-lg-4">
        <form asp-controller="Identity" asp-action="Login" method="post">
            <div asp-validation-summary="ModelOnly"></div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email">
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password"></label>
                <input asp-for="Password" type="password" class="form-control" id="password" placeholder="Password">
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>
</div>

HotelSystem.Admin/Views/Shared/_Layout.cshtml
@using HotelSystem.Common.Infrastructure;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HotelSystem.Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div class="container">
                    @if (this.User.IsAdministrator())
                    {
                        <a class="navbar-brand" asp-area="" asp-controller="Statistics" asp-action="Index">Hotel System Administration</a>
                        <a class="float-left" asp-area="" asp-controller="Guests" asp-action="Index">Guests</a>
                        <a class="float-right" asp-area="" asp-controller="Identity" asp-action="Logout">Logout</a> }
                    else
                    {
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Car Rental System Administration</a>}

                    <button class="navbar-toggler"
                            type="button"
                            data-toggle="collapse"
                            data-target=".navbar-collapse"
                            aria-controls="navbarSupportedContent"
                            aria-expanded="false"
                            aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - HotelSystem.Admin - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

HotelSystem.Admin/Views/Statistics/Index.cshtml
@model StatisticsOutputModel

<h1 class="text-center">@Model.TotalReservations total made reservations!</h1>